# Generated by Django 5.2.1 on 2025-05-18 15:16

import django.db.models.deletion
import signsecure.documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('file', models.FileField(upload_to='')),
                ('file_type', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('document_created', 'Document Created'), ('document_sent', 'Document Sent'), ('document_viewed', 'Document Viewed'), ('document_signed', 'Document Signed'), ('document_completed', 'Document Completed'), ('document_uploaded', 'Document uploaded'), ('signer_added', 'Signer added'), ('field_added', 'Field added')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='documents.document')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.TextField(default=signsecure.documents.models.generate_default_token, unique=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='documents.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('signature', 'Signature'), ('date', 'Date'), ('text', 'Text')], max_length=20)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('page', models.PositiveIntegerField()),
                ('required', models.BooleanField(default=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.document')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.signer')),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view'],
            },
        ),
    ]
