# Generated by Django 5.2.1 on 2025-05-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='height',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='width',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='x',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='y',
            field=models.DecimalField(decimal_places=50, max_digits=50),
        ),
    ]
