# Generated by Django 5.2.1 on 2025-05-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_formfield_height_alter_formfield_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='y',
            field=models.FloatField(),
        ),
    ]
